name: Calendar Metrics
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:

  full_year_calendar:
    name: Full-year calendar
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: env.METRICS_TOKEN
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year