- name: Recent GitHub Activity - Profile Readme

on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 60 minutes.

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity

    steps:
       uses: Readme-Workflows/recent-activity@v2.4.1
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Updated README with recent activity"
          MAX_LINES: 10

            
